= PuffinPlot development notes

PuffinPlot is a program for palaeomagnetic data plotting and analysis,
written by Pontus Lurcock. This readme describes the requirements for
building PuffinPlot and its documentation from source, and is intended
for developers rather than users. Users are advised to download the
latest PuffinPlot release from the project website at
http://talvi.net/puffinplot/ and consult the included user manual.

== Building PuffinPlot

PuffinPlot is structured as a Maven project, and can be built by running
`mvn package` in the root directory. Most dependencies will be automatically
downloaded and installed by Maven. The only external dependency is git,
which is used to incorporate version information into the build.

PuffinPlot is currently developed mainly in
https://netbeans.apache.org/[Apache Netbeans], and the `nbactions.xml` file
provides some NetBeans-specific Maven actions, but development is not tied
to any specific IDE. In particular, PuffinPlot's Swing GUI does not make use of
the NetBeans Matisse GUI designer.

PuffinPlot can optionally make use of Jython; the required Jython package can be
dynamically downloaded, installed, and used by PuffinPlot at runtime, but it is
not a build-time dependency.

== Bug tracking

PuffinPlot uses the Bugs Everywhere bug-tracking system; the bug
database lives within the repository itself, in the `.be` folder. Bugs
Everywhere is available from http://www.bugseverywhere.org/ .
