--- !ditz.rubyforge.org,2008-03-06/project 
name: PuffinPlot
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: PuffinPlot
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-05 20:42:06.583126 Z
    - Pontus Lurcock <pont@talvi.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-05 20:46:43.692613 Z
    - Pontus Lurcock <pont@talvi.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-04-05 20:48:50.343426 Z
    - Pontus Lurcock <pont@talvi.net>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.9"
  status: :released
  release_time: 2009-04-05 23:55:09.883268 Z
  log_events: 
  - - 2009-04-05 23:48:35.873072 Z
    - Pontus Lurcock <pont@talvi.net>
    - created
    - ""
  - - 2009-04-05 23:55:09.883299 Z
    - Pontus Lurcock <pont@talvi.net>
    - released
    - ""
